In [2]:
from barista_bench.eval import run_model
from barista_bench.schema import Order, OrderList
from barista_bench.prompt.default import BaristaPrompt
from barista_bench.eval.run_model import load_training_set

from barista_bench.eval.run_model import evaluate_api_model
%load_ext autoreload
%autoreload 2



df = load_training_set('../data/train.csv')
df['expected_order'] = df['expected_json'].apply(
    lambda x: OrderList.model_validate_json(x)
)
sample = df[df['expected_json'].apply(len) > 300].sample(3)
examples = sample[['order', 'expected_json']].values.tolist()
df = df[~df.index.isin(sample.index)]
prompt = BaristaPrompt('default.txt', examples)

out = evaluate_api_model('qwen/qwen-2.5-7b-instruct',prompt, df.sample(10))
out

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

100%|██████████| 10/10 [00:25<00:00,  2.54s/it]

,id,order,expected_json,expected_order,pred,loss
317,317,Start me off with four Short COLD BREW include...,"{""items"": [{""name"": ""Cold Brew"", ""size"": ""Shor...","items=[Order(name='Cold Brew', size='Short', q...","{""items"":[{""name"":""Cold Brew"",""size"":""Short"",""...",13.50
44,44,"I'll have a short Cold Brew, paired with a Tal...","{""items"": [{""name"": ""Cold Brew"", ""size"": ""Shor...","items=[Order(name='Cold Brew', size='Short', q...","{""items"":[{""name"":""Cold Brew"",""size"":""Short"",""...",5.80
103,103,"I'll take a Short iced coffee, like wait, chan...","{""items"": [{""name"": ""Iced Coffee"", ""size"": ""Sh...","items=[Order(name='Iced Coffee', size='Short',...","{""items"":[{""name"":""Iced Coffee"",""size"":""Short""...",12.50
384,384,Hook me up with couple of venti hot chocolates...,"{""items"": [{""name"": ""Hot Chocolate"", ""size"": ""...","items=[Order(name='Hot Chocolate', size='Venti...","{""items"":[{""name"":""Hot Chocolate"",""size"":""Vent...",16.80
483,483,Let me get pair of Grande EARL GREY TEA and cl...,"{""items"": [{""name"": ""Earl Grey Tea"", ""size"": ""...","items=[Order(name='Earl Grey Tea', size='Grand...","{""items"":[{""name"":""Earl Grey Tea"",""size"":""Gran...",6.60
400,400,Can I get five grande frappe (coffee) uh add C...,"{""items"": [{""name"": ""Frappe (Coffee)"", ""size"":...","items=[Order(name='Frappe (Coffee)', size='Gra...","{""items"":[{""name"":""Frappe (Coffee)"",""size"":""Gr...",29.40
99,99,Hook me up with one venti caramel macchiato. N...,"{""items"": [{""name"": ""Caramel Macchiato"", ""size...","items=[Order(name='Caramel Macchiato', size='V...","{""items"":[{""name"":""Caramel Macchiato"",""size"":""...",7.75
318,318,"May I get triple you know, short flat whites, ...","{""items"": [{""name"": ""Flat White"", ""size"": ""Sho...","items=[Order(name='Flat White', size='Short', ...","{""items"":[{""name"":""Flat White"",""size"":""Short"",...",10.00
411,411,Grab me pair of like tall Cold Brew.,"{""items"": [{""name"": ""Cold Brew"", ""size"": ""Tall...","items=[Order(name='Cold Brew', size='Tall', qu...","{""items"":[{""name"":""Cold Brew"",""size"":""Tall"",""q...",0.00
214,214,"Start me off with a few bagels wait no, make i...","{""items"": [{""name"": ""Bagel"", ""size"": null, ""qu...","items=[Order(name='Bagel', size=None, quantity...","{""items"":[{""name"":""Bagel"",""size"":null,""quantit...",10.55

In [7]:
print(out[out['loss'] > 20]['expected_json'].iloc[0])

{"items": [{"name": "Frappe (Coffee)", "size": "Grande", "quantity": 5, "modifiers": ["Coconut Milk"]}, {"name": "Strawberry Smoothie", "size": "Tall", "quantity": 2, "modifiers": ["Cold Foam", "Caramel Drizzle"]}, {"name": "Mocha", "size": "Short", "quantity": 2, "modifiers": ["Peppermint Syrup"]}], "total_price": 59.0}

In [8]:
print(out[out['loss'] > 20]['pred'].iloc[0])

{"items":[{"name":"Frappe (Coffee)","size":"Grande","quantity":5,"modifiers":["Coconut Milk"]},{"name":"Strawberry Smoothie","size":"Tall","quantity":2,"modifiers":["Cold Foam","Caramel Drizzle"]},{"name":"Mocha","size":"Short","quantity":2,"modifiers":["Peppermint Syrup"]}],"total_price":29.6}

In [32]:
import re 

ptn =  r'```json\s*([\s\S]*?)\s*```'

json_code = out.iloc[1]['pred']['choices'][0]['message']['content']
matches = re.findall(ptn, json_code)
OrderList.model_validate_json(matches[0])
# matches
# matches[0]

OrderList(items=[Order(name='Cold Brew', size='Short', quantity=1, modifiers=[]), Order(name='Iced Coffee', size='Tall', quantity=1, modifiers=['Hazelnut Syrup'])], total_price=9.75)

In [30]:
o1 = {
    'name' : 'Espresso',
    'size': 'Short',
    'quantity':2 ,
    'modifiers': ['whip cream']

}
o2 = {
    'name' : 'Espresso',
    'size': 'Short',
    'quantity':2 ,
    'modifiers': ['extra shot']

}
o1 = Order.model_validate(o1)
o2 = Order.model_validate(o2)

run_model.order_loss(o1, o2)

0.5

,id,order,expected_json,expected_order
0,0,Lemme get one tall Strawberry Smoothie include...,"{""items"": [{""name"": ""Drip Coffee"", ""size"": ""Ve...","items=[Order(name='Drip Coffee', size='Venti',..."
1,1,I'd like to order single trenta espresso add o...,"{""items"": [{""name"": ""Espresso"", ""size"": ""Trent...","items=[Order(name='Espresso', size='Trenta', q..."
2,2,Could I have single trenta mocha plus peppermi...,"{""items"": [{""name"": ""Mocha"", ""size"": ""Trenta"",...","items=[Order(name='Mocha', size='Trenta', quan..."
3,3,Grab me four avocado toasts.,"{""items"": [{""name"": ""Avocado Toast"", ""size"": n...","items=[Order(name='Avocado Toast', size=None, ..."
4,4,I'm craving couple of VENTI frappe (mocha)s in...,"{""items"": [{""name"": ""Frappe (Mocha)"", ""size"": ...","items=[Order(name='Frappe (Mocha)', size='Vent..."
...,...,...,...,...
495,495,May I get two Tall iced coffees include skim m...,"{""items"": [{""name"": ""Iced Coffee"", ""size"": ""Ta...","items=[Order(name='Iced Coffee', size='Tall', ..."
496,496,I'm feeling like four trenta flat white add oa...,"{""items"": [{""name"": ""Flat White"", ""size"": ""Tre...","items=[Order(name='Flat White', size='Trenta',..."
497,497,Start me off with couple of tall Flat Whites a...,"{""items"": [{""name"": ""Flat White"", ""size"": ""Tal...","items=[Order(name='Flat White', size='Tall', q..."
498,498,Grab me two short like Cold Brews... wait canc...,"{""items"": [{""name"": ""Strawberry Smoothie"", ""si...","items=[Order(name='Strawberry Smoothie', size=..."
499,499,I'm feeling like a Blueberry Muffin... bump th...,"{""items"": [{""name"": ""Blueberry Muffin"", ""size""...","items=[Order(name='Blueberry Muffin', size=Non..."

In [ ]:
sample = df[df['expected_json'].apply(len) > 300].sample(3)
# not_sample = sample.index
examples = sample[['order', 'expected_json']].values.tolist()
# df.loc[not_sample]
df = df[~df.index.isin(sample.index)]




out = prompt.format_llm_input('I would like a large latte with almond milk and a blueberry muffin.')
out

[{'role': 'system',
  'content': 'You are a Barista POS System designed to take customer orders and output JSON corresponding to what the customer has ordered. The cafe that you are working with has the following menu and instructions:\n\n# BARISTA BENCH: OFFICIAL MENU & RULES (V2)\n\n## 1. HOT COFFEES\n- Espresso: $3.00 (Default: Solo)\n- Americano: $3.50\n- Drip Coffee: $2.50\n- Latte: $4.50 (Default: Whole Milk)\n- Cappuccino: $4.50 (Default: Whole Milk)\n- Flat White: $4.75 (Default: Whole Milk)\n- Mocha: $5.00 (Default: Whole Milk, Whip)\n- Caramel Macchiato: $5.25 (Default: Whole Milk, Drizzle)\n\n## 2. COLD / BLENDED\n- Cold Brew: $4.25\n- Iced Coffee: $3.00\n- Frappe (Coffee): $5.50 (Default: Whole Milk, Whip)\n- Frappe (Mocha): $5.75 (Default: Whole Milk, Whip)\n- Strawberry Smoothie: $6.00 (No Milk)\n\n## 3. TEAS & OTHERS\n- Chai Latte: $4.75 (Default: Whole Milk)\n- Matcha Latte: $5.25 (Default: Whole Milk)\n- Earl Grey Tea: $3.00\n- Green Tea: $3.00\n- Hot Chocolate: $4.00 (Default: Whole Milk, Whip)\n\n## 4. FOOD (No modifiers allowed usually)\n- Butter Croissant: $3.50\n- Blueberry Muffin: $3.75\n- Bagel: $2.50\n- Avocado Toast: $7.00\n- Bacon Gouda Sandwich: $5.50\n\n## 5. SIZES (Drink Price Adjustments)\n- Short (8oz): -$0.50\n- Tall (12oz): +$0.00 (Base)\n- Grande (16oz): +$0.50\n- Venti (20oz): +$1.00\n- Trenta (30oz): +$1.50 (Cold drinks only)\n\n## 6. MODIFIERS\n### Milks (Replaces default)\n- Oat Milk: +$0.80\n- Almond Milk: +$0.60\n- Soy Milk: +$0.60\n- Coconut Milk: +$0.70\n- Breve (Half & Half): +$0.80\n- Skim Milk: +$0.00\n\n### Syrups (Add-on)\n- Vanilla Syrup: +$0.50\n- Caramel Syrup: +$0.50\n- Hazelnut Syrup: +$0.50\n- Peppermint Syrup: +$0.50\n- Sugar Free Vanilla: +$0.50\n- Classic Syrup: +$0.00\n\n### Toppings / Texture\n- Extra Shot: +$1.00\n- Whip Cream: +$0.50\n- No Whip: +$0.00\n- Cold Foam: +$1.25\n- Caramel Drizzle: +$0.50\n- Extra Hot: +$0.00\n- Light Ice: +$0.00\n- No Ice: +$0.00\n\n## 7. LOGIC RULES\n- **Replacement:** If a user asks for a milk (e.g., Oat), it replaces the default.\n- **Cancellation:** If a user says "No Whip" on a drink that has Whip (like Mocha), the price does not change, but "No Whip" is noted.\n- **Double Mods:** Syrups stack (Vanilla + Caramel = +$1.00).\n- **Food:** Food items do not have sizes.\n\nAssume that the customer is always correct, if the customer ordered something it will be on the menu so choose the closest item on the menu.\n\n\nFORMAT: \nReturn ONLY a JSON Object. Do not explain your work. The JSON Schema has to strictly follow the schema below:\n\n\n{\'$defs\': {\'Order\': {\'properties\': {\'name\': {\'title\': \'Name\', \'type\': \'string\'}, \'size\': {\'anyOf\': [{\'type\': \'string\'}, {\'type\': \'null\'}], \'title\': \'Size\'}, \'quantity\': {\'title\': \'Quantity\', \'type\': \'integer\'}, \'modifiers\': {\'items\': {\'type\': \'string\'}, \'title\': \'Modifiers\', \'type\': \'array\'}}, \'required\': [\'name\', \'size\', \'quantity\', \'modifiers\'], \'title\': \'Order\', \'type\': \'object\'}}, \'properties\': {\'items\': {\'items\': {\'$ref\': \'#/$defs/Order\'}, \'title\': \'Items\', \'type\': \'array\'}, \'total_price\': {\'title\': \'Total Price\', \'type\': \'number\'}}, \'required\': [\'items\', \'total_price\'], \'title\': \'OrderList\', \'type\': \'object\'}\n'},
 {'role': 'user',
  'content': '\nHere are some examples of customer orders and the corresponding JSON output:\n\nCustomer Order:\nLet me get four Venti Espresso plus Almond Milk... actually nevermind Almond Milk wait extra shot plus Caramel Drizzle with classic syrup. Then give me two Trenta cappuccinos plus Peppermint Syrup. actually nevermind Peppermint um Syrup - Whip Cream plus classic syrup. Oh, and add a Short Iced Coffee, paired with one short um frappe (coffee).\n\nJSON Output:\n{"items": [{"name": "Espresso", "size": "Venti", "quantity": 4, "modifiers": ["Extra Shot", "Caramel Drizzle", "Classic Syrup"]}, {"name": "Cappuccino", "size": "Trenta", "quantity": 2, "modifiers": ["Whip Cream", "Classic Syrup"]}, {"name": "Iced Coffee", "size": "Short", "quantity": 1, "modifiers": []}, {"name": "Frappe (Coffee)", "size": "Short", "quantity": 1, "modifiers": []}], "total_price": 42.5}\n\nCustomer Order:\nGrab me two avocado um toasts, plus two short strawberry you know, smoothies plus skim milk. Oh, and add a grande espresso plus a Bacon Gouda Sandwich. actually make that you know, two.\n\nJSON Output:\n{"items": [{"name": "Avocado Toast", "size": null, "quantity": 2, "modifiers": []}, {"name": "Strawberry Smoothie", "size": "Short", "quantity": 2, "modifiers": ["Skim Milk"]}, {"name": "Espresso", "size": "Grande", "quantity": 1, "modifiers": []}, {"name": "Bacon Gouda Sandwich", "size": null, "quantity": 2, "modifiers": []}], "total_price": 39.5}\n\nCustomer Order:\nCan I get a literally few short flat whites include almond milk, coupled with a venti espresso include Hazelnut Syrup and four trenta Americanos and Extra Shot add caramel drizzle, and also one short uh americano with light ice add Sugar Free Vanilla wait actually make that triple.\n\nJSON Output:\n{"items": [{"name": "Flat White", "size": "Short", "quantity": 3, "modifiers": ["Almond Milk"]}, {"name": "Espresso", "size": "Venti", "quantity": 1, "modifiers": ["Hazelnut Syrup"]}, {"name": "Americano", "size": "Trenta", "quantity": 4, "modifiers": ["Extra Shot", "Caramel Drizzle"]}, {"name": "Americano", "size": "Short", "quantity": 3, "modifiers": ["Light Ice", "Sugar Free Vanilla"]}], "total_price": 55.55}\n now do the same for this customer order I would like a large latte with almond milk and a blueberry muffin.\n                '}]

In [ ]:
from barista_bench.eval.run_model import evaluate_api_model

out = evaluate_api_model('qwen/qwen-2.5-7b-instruct',prompt, df)
out

 36%|███▌      | 168/464 [07:44<14:22,  2.91s/it]

In [64]:
out['choices'][0]['message']['content']

'{\n    "items": [\n        {"name": "Strawberry Smoothie", "size": "Tall", "quantity": 1, "modifiers": []},\n        {"name": "Drip Coffee", "size": "Venti", "quantity": 1, "modifiers": ["Extra Hot"]},\n        {"name": "Chai Latte", "size": "Trenta", "quantity": 3, "modifiers": ["Caramel Drizzle"]},\n        {"name": "Mocha", "size": "Short", "quantity": 2, "modifiers": ["Sugar Free Vanilla"]}\n    ],\n    "total_price": 23.05\n}'

In [18]:

for ol in df['expected_order']:
    # print(type(ol))
    for it in ol.items:
        if not len(it.modifiers):
            print(it)
    # break

name='Mocha' size='Short' quantity=2 modifiers=[]
name='Earl Grey Tea' size='Tall' quantity=1 modifiers=[]
name='Avocado Toast' size=None quantity=4 modifiers=[]
name='Iced Coffee' size='Tall' quantity=1 modifiers=[]
name='Butter Croissant' size=None quantity=4 modifiers=[]
name='Green Tea' size='Trenta' quantity=1 modifiers=[]
name='Chai Latte' size='Tall' quantity=2 modifiers=[]
name='Matcha Latte' size='Short' quantity=1 modifiers=[]
name='Earl Grey Tea' size='Venti' quantity=3 modifiers=[]
name='Bagel' size=None quantity=2 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=3 modifiers=[]
name='Avocado Toast' size=None quantity=2 modifiers=[]
name='Frappe (Mocha)' size='Venti' quantity=3 modifiers=[]
name='Mocha' size='Tall' quantity=1 modifiers=[]
name='Matcha Latte' size='Short' quantity=3 modifiers=[]
name='Caramel Macchiato' size='Trenta' quantity=3 modifiers=[]
name='Earl Grey Tea' size='Venti' quantity=1 modifiers=[]
name='Green Tea' size='Trenta' quantity=3 modifiers=[]
name='Drip Coffee' size='Short' quantity=3 modifiers=[]
name='Flat White' size='Trenta' quantity=2 modifiers=[]
name='Drip Coffee' size='Tall' quantity=1 modifiers=[]
name='Mocha' size='Trenta' quantity=4 modifiers=[]
name='Earl Grey Tea' size='Short' quantity=2 modifiers=[]
name='Cappuccino' size='Short' quantity=1 modifiers=[]
name='Mocha' size='Tall' quantity=2 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=1 modifiers=[]
name='Frappe (Mocha)' size='Tall' quantity=5 modifiers=[]
name='Hot Chocolate' size='Trenta' quantity=1 modifiers=[]
name='Matcha Latte' size='Tall' quantity=2 modifiers=[]
name='Espresso' size='Grande' quantity=3 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=1 modifiers=[]
name='Hot Chocolate' size='Trenta' quantity=3 modifiers=[]
name='Blueberry Muffin' size=None quantity=2 modifiers=[]
name='Cappuccino' size='Tall' quantity=5 modifiers=[]
name='Blueberry Muffin' size=None quantity=1 modifiers=[]
name='Chai Latte' size='Tall' quantity=2 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=2 modifiers=[]
name='Blueberry Muffin' size=None quantity=4 modifiers=[]
name='Americano' size='Trenta' quantity=1 modifiers=[]
name='Caramel Macchiato' size='Trenta' quantity=1 modifiers=[]
name='Iced Coffee' size='Trenta' quantity=1 modifiers=[]
name='Bagel' size=None quantity=3 modifiers=[]
name='Frappe (Mocha)' size='Grande' quantity=4 modifiers=[]
name='Blueberry Muffin' size=None quantity=1 modifiers=[]
name='Hot Chocolate' size='Short' quantity=3 modifiers=[]
name='Blueberry Muffin' size=None quantity=4 modifiers=[]
name='Frappe (Mocha)' size='Venti' quantity=2 modifiers=[]
name='Butter Croissant' size=None quantity=3 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=2 modifiers=[]
name='Cold Brew' size='Short' quantity=1 modifiers=[]
name='Mocha' size='Venti' quantity=2 modifiers=[]
name='Frappe (Mocha)' size='Tall' quantity=5 modifiers=[]
name='Blueberry Muffin' size=None quantity=2 modifiers=[]
name='Strawberry Smoothie' size='Grande' quantity=2 modifiers=[]
name='Earl Grey Tea' size='Trenta' quantity=4 modifiers=[]
name='Chai Latte' size='Short' quantity=4 modifiers=[]
name='Mocha' size='Tall' quantity=4 modifiers=[]
name='Latte' size='Tall' quantity=1 modifiers=[]
name='Flat White' size='Grande' quantity=1 modifiers=[]
name='Earl Grey Tea' size='Trenta' quantity=1 modifiers=[]
name='Strawberry Smoothie' size='Trenta' quantity=3 modifiers=[]
name='Cappuccino' size='Grande' quantity=1 modifiers=[]
name='Cappuccino' size='Tall' quantity=3 modifiers=[]
name='Latte' size='Short' quantity=1 modifiers=[]
name='Green Tea' size='Short' quantity=2 modifiers=[]
name='Avocado Toast' size=None quantity=2 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=1 modifiers=[]
name='Iced Coffee' size='Short' quantity=2 modifiers=[]
name='Hot Chocolate' size='Grande' quantity=3 modifiers=[]
name='Cappuccino' size='Trenta' quantity=1 modifiers=[]
name='Hot Chocolate' size='Short' quantity=1 modifiers=[]
name='Frappe (Mocha)' size='Tall' quantity=2 modifiers=[]
name='Blueberry Muffin' size=None quantity=1 modifiers=[]
name='Bagel' size=None quantity=3 modifiers=[]
name='Cold Brew' size='Tall' quantity=2 modifiers=[]
name='Cappuccino' size='Trenta' quantity=1 modifiers=[]
name='Cappuccino' size='Tall' quantity=1 modifiers=[]
name='Frappe (Coffee)' size='Grande' quantity=3 modifiers=[]
name='Espresso' size='Short' quantity=2 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=4 modifiers=[]
name='Iced Coffee' size='Short' quantity=5 modifiers=[]
name='Frappe (Coffee)' size='Tall' quantity=1 modifiers=[]
name='Blueberry Muffin' size=None quantity=2 modifiers=[]
name='Chai Latte' size='Grande' quantity=3 modifiers=[]
name='Bagel' size=None quantity=1 modifiers=[]
name='Cold Brew' size='Tall' quantity=3 modifiers=[]
name='Bagel' size=None quantity=2 modifiers=[]
name='Caramel Macchiato' size='Tall' quantity=1 modifiers=[]
name='Frappe (Coffee)' size='Short' quantity=2 modifiers=[]
name='Caramel Macchiato' size='Tall' quantity=5 modifiers=[]
name='Caramel Macchiato' size='Tall' quantity=5 modifiers=[]
name='Cappuccino' size='Venti' quantity=1 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=3 modifiers=[]
name='Green Tea' size='Grande' quantity=1 modifiers=[]
name='Matcha Latte' size='Short' quantity=2 modifiers=[]
name='Chai Latte' size='Grande' quantity=3 modifiers=[]
name='Flat White' size='Grande' quantity=3 modifiers=[]
name='Butter Croissant' size=None quantity=1 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=1 modifiers=[]
name='Iced Coffee' size='Tall' quantity=3 modifiers=[]
name='Avocado Toast' size=None quantity=3 modifiers=[]
name='Bagel' size=None quantity=8 modifiers=[]
name='Flat White' size='Tall' quantity=2 modifiers=[]
name='Matcha Latte' size='Grande' quantity=2 modifiers=[]
name='Caramel Macchiato' size='Grande' quantity=1 modifiers=[]
name='Frappe (Coffee)' size='Grande' quantity=1 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=4 modifiers=[]
name='Chai Latte' size='Tall' quantity=2 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=1 modifiers=[]
name='Frappe (Mocha)' size='Grande' quantity=5 modifiers=[]
name='Caramel Macchiato' size='Grande' quantity=1 modifiers=[]
name='Cappuccino' size='Grande' quantity=3 modifiers=[]
name='Espresso' size='Grande' quantity=3 modifiers=[]
name='Caramel Macchiato' size='Venti' quantity=1 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=1 modifiers=[]
name='Green Tea' size='Venti' quantity=5 modifiers=[]
name='Butter Croissant' size=None quantity=3 modifiers=[]
name='Green Tea' size='Short' quantity=2 modifiers=[]
name='Cold Brew' size='Tall' quantity=1 modifiers=[]
name='Blueberry Muffin' size=None quantity=1 modifiers=[]
name='Bagel' size=None quantity=5 modifiers=[]
name='Iced Coffee' size='Short' quantity=3 modifiers=[]
name='Bagel' size=None quantity=2 modifiers=[]
name='Blueberry Muffin' size=None quantity=1 modifiers=[]
name='Green Tea' size='Grande' quantity=4 modifiers=[]
name='Chai Latte' size='Venti' quantity=2 modifiers=[]
name='Hot Chocolate' size='Tall' quantity=4 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=1 modifiers=[]
name='Americano' size='Grande' quantity=2 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=2 modifiers=[]
name='Chai Latte' size='Short' quantity=3 modifiers=[]
name='Blueberry Muffin' size=None quantity=5 modifiers=[]
name='Bagel' size=None quantity=2 modifiers=[]
name='Iced Coffee' size='Trenta' quantity=3 modifiers=[]
name='Americano' size='Tall' quantity=2 modifiers=[]
name='Americano' size='Venti' quantity=2 modifiers=[]
name='Frappe (Mocha)' size='Venti' quantity=1 modifiers=[]
name='Bagel' size=None quantity=1 modifiers=[]
name='Frappe (Mocha)' size='Tall' quantity=4 modifiers=[]
name='Bagel' size=None quantity=2 modifiers=[]
name='Avocado Toast' size=None quantity=2 modifiers=[]
name='Avocado Toast' size=None quantity=1 modifiers=[]
name='Cappuccino' size='Trenta' quantity=1 modifiers=[]
name='Drip Coffee' size='Short' quantity=5 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=2 modifiers=[]
name='Blueberry Muffin' size=None quantity=5 modifiers=[]
name='Bagel' size=None quantity=3 modifiers=[]
name='Strawberry Smoothie' size='Tall' quantity=1 modifiers=[]
name='Drip Coffee' size='Grande' quantity=1 modifiers=[]
name='Avocado Toast' size=None quantity=3 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=4 modifiers=[]
name='Butter Croissant' size=None quantity=2 modifiers=[]
name='Blueberry Muffin' size=None quantity=1 modifiers=[]
name='Hot Chocolate' size='Tall' quantity=1 modifiers=[]
name='Blueberry Muffin' size=None quantity=3 modifiers=[]
name='Avocado Toast' size=None quantity=5 modifiers=[]
name='Bagel' size=None quantity=2 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=2 modifiers=[]
name='Hot Chocolate' size='Venti' quantity=3 modifiers=[]
name='Drip Coffee' size='Tall' quantity=1 modifiers=[]
name='Flat White' size='Venti' quantity=2 modifiers=[]
name='Americano' size='Trenta' quantity=3 modifiers=[]
name='Earl Grey Tea' size='Grande' quantity=1 modifiers=[]
name='Bagel' size=None quantity=2 modifiers=[]
name='Butter Croissant' size=None quantity=1 modifiers=[]
name='Bagel' size=None quantity=1 modifiers=[]
name='Avocado Toast' size=None quantity=1 modifiers=[]
name='Latte' size='Venti' quantity=1 modifiers=[]
name='Green Tea' size='Short' quantity=1 modifiers=[]
name='Drip Coffee' size='Tall' quantity=1 modifiers=[]
name='Blueberry Muffin' size=None quantity=1 modifiers=[]
name='Blueberry Muffin' size=None quantity=1 modifiers=[]
name='Mocha' size='Venti' quantity=2 modifiers=[]
name='Drip Coffee' size='Trenta' quantity=1 modifiers=[]
name='Flat White' size='Short' quantity=2 modifiers=[]
name='Frappe (Mocha)' size='Trenta' quantity=4 modifiers=[]
name='Iced Coffee' size='Trenta' quantity=3 modifiers=[]
name='Espresso' size='Tall' quantity=2 modifiers=[]
name='Hot Chocolate' size='Tall' quantity=2 modifiers=[]
name='Green Tea' size='Trenta' quantity=1 modifiers=[]
name='Cappuccino' size='Grande' quantity=2 modifiers=[]
name='Cappuccino' size='Venti' quantity=1 modifiers=[]
name='Bagel' size=None quantity=5 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=3 modifiers=[]
name='Green Tea' size='Grande' quantity=5 modifiers=[]
name='Strawberry Smoothie' size='Venti' quantity=3 modifiers=[]
name='Mocha' size='Trenta' quantity=5 modifiers=[]
name='Frappe (Mocha)' size='Tall' quantity=1 modifiers=[]
name='Mocha' size='Grande' quantity=2 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=1 modifiers=[]
name='Espresso' size='Trenta' quantity=2 modifiers=[]
name='Blueberry Muffin' size=None quantity=5 modifiers=[]
name='Earl Grey Tea' size='Trenta' quantity=1 modifiers=[]
name='Butter Croissant' size=None quantity=5 modifiers=[]
name='Latte' size='Grande' quantity=2 modifiers=[]
name='Blueberry Muffin' size=None quantity=2 modifiers=[]
name='Avocado Toast' size=None quantity=1 modifiers=[]
name='Earl Grey Tea' size='Grande' quantity=1 modifiers=[]
name='Butter Croissant' size=None quantity=2 modifiers=[]
name='Chai Latte' size='Trenta' quantity=4 modifiers=[]
name='Blueberry Muffin' size=None quantity=1 modifiers=[]
name='Mocha' size='Venti' quantity=1 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=2 modifiers=[]
name='Chai Latte' size='Trenta' quantity=3 modifiers=[]
name='Avocado Toast' size=None quantity=1 modifiers=[]
name='Caramel Macchiato' size='Grande' quantity=2 modifiers=[]
name='Frappe (Coffee)' size='Grande' quantity=1 modifiers=[]
name='Bagel' size=None quantity=1 modifiers=[]
name='Green Tea' size='Tall' quantity=2 modifiers=[]
name='Bagel' size=None quantity=1 modifiers=[]
name='Hot Chocolate' size='Trenta' quantity=2 modifiers=[]
name='Espresso' size='Short' quantity=1 modifiers=[]
name='Drip Coffee' size='Short' quantity=1 modifiers=[]
name='Latte' size='Trenta' quantity=5 modifiers=[]
name='Butter Croissant' size=None quantity=2 modifiers=[]
name='Caramel Macchiato' size='Venti' quantity=3 modifiers=[]
name='Strawberry Smoothie' size='Short' quantity=5 modifiers=[]
name='Chai Latte' size='Tall' quantity=3 modifiers=[]
name='Espresso' size='Tall' quantity=2 modifiers=[]
name='Avocado Toast' size=None quantity=1 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=5 modifiers=[]
name='Avocado Toast' size=None quantity=1 modifiers=[]
name='Matcha Latte' size='Venti' quantity=2 modifiers=[]
name='Earl Grey Tea' size='Short' quantity=2 modifiers=[]
name='Flat White' size='Venti' quantity=1 modifiers=[]
name='Cold Brew' size='Trenta' quantity=1 modifiers=[]
name='Green Tea' size='Trenta' quantity=2 modifiers=[]
name='Drip Coffee' size='Grande' quantity=3 modifiers=[]
name='Americano' size='Short' quantity=3 modifiers=[]
name='Green Tea' size='Short' quantity=1 modifiers=[]
name='Flat White' size='Trenta' quantity=3 modifiers=[]
name='Espresso' size='Venti' quantity=1 modifiers=[]
name='Latte' size='Venti' quantity=3 modifiers=[]
name='Bagel' size=None quantity=1 modifiers=[]
name='Avocado Toast' size=None quantity=1 modifiers=[]
name='Americano' size='Tall' quantity=2 modifiers=[]
name='Butter Croissant' size=None quantity=3 modifiers=[]
name='Frappe (Coffee)' size='Trenta' quantity=2 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=1 modifiers=[]
name='Matcha Latte' size='Venti' quantity=5 modifiers=[]
name='Chai Latte' size='Grande' quantity=3 modifiers=[]
name='Iced Coffee' size='Tall' quantity=4 modifiers=[]
name='Blueberry Muffin' size=None quantity=5 modifiers=[]
name='Avocado Toast' size=None quantity=1 modifiers=[]
name='Butter Croissant' size=None quantity=2 modifiers=[]
name='Matcha Latte' size='Grande' quantity=2 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=2 modifiers=[]
name='Green Tea' size='Trenta' quantity=1 modifiers=[]
name='Blueberry Muffin' size=None quantity=1 modifiers=[]
name='Earl Grey Tea' size='Short' quantity=3 modifiers=[]
name='Avocado Toast' size=None quantity=2 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=2 modifiers=[]
name='Blueberry Muffin' size=None quantity=5 modifiers=[]
name='Chai Latte' size='Grande' quantity=1 modifiers=[]
name='Hot Chocolate' size='Short' quantity=3 modifiers=[]
name='Frappe (Mocha)' size='Grande' quantity=2 modifiers=[]
name='Green Tea' size='Grande' quantity=3 modifiers=[]
name='Bagel' size=None quantity=1 modifiers=[]
name='Caramel Macchiato' size='Venti' quantity=1 modifiers=[]
name='Strawberry Smoothie' size='Short' quantity=1 modifiers=[]
name='Caramel Macchiato' size='Trenta' quantity=1 modifiers=[]
name='Matcha Latte' size='Short' quantity=4 modifiers=[]
name='Latte' size='Trenta' quantity=1 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=3 modifiers=[]
name='Cappuccino' size='Venti' quantity=1 modifiers=[]
name='Bagel' size=None quantity=3 modifiers=[]
name='Caramel Macchiato' size='Venti' quantity=3 modifiers=[]
name='Espresso' size='Tall' quantity=3 modifiers=[]
name='Blueberry Muffin' size=None quantity=1 modifiers=[]
name='Chai Latte' size='Venti' quantity=2 modifiers=[]
name='Drip Coffee' size='Trenta' quantity=3 modifiers=[]
name='Avocado Toast' size=None quantity=1 modifiers=[]
name='Iced Coffee' size='Venti' quantity=1 modifiers=[]
name='Caramel Macchiato' size='Short' quantity=3 modifiers=[]
name='Butter Croissant' size=None quantity=1 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=2 modifiers=[]
name='Matcha Latte' size='Trenta' quantity=2 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=3 modifiers=[]
name='Bagel' size=None quantity=4 modifiers=[]
name='Latte' size='Grande' quantity=4 modifiers=[]
name='Chai Latte' size='Venti' quantity=2 modifiers=[]
name='Flat White' size='Tall' quantity=4 modifiers=[]
name='Americano' size='Trenta' quantity=3 modifiers=[]
name='Bagel' size=None quantity=2 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=2 modifiers=[]
name='Flat White' size='Grande' quantity=4 modifiers=[]
name='Butter Croissant' size=None quantity=3 modifiers=[]
name='Frappe (Mocha)' size='Trenta' quantity=1 modifiers=[]
name='Strawberry Smoothie' size='Tall' quantity=2 modifiers=[]
name='Cappuccino' size='Grande' quantity=1 modifiers=[]
name='Drip Coffee' size='Trenta' quantity=1 modifiers=[]
name='Green Tea' size='Trenta' quantity=3 modifiers=[]
name='Bagel' size=None quantity=5 modifiers=[]
name='Hot Chocolate' size='Grande' quantity=3 modifiers=[]
name='Flat White' size='Trenta' quantity=1 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=5 modifiers=[]
name='Bagel' size=None quantity=1 modifiers=[]
name='Strawberry Smoothie' size='Venti' quantity=3 modifiers=[]
name='Frappe (Mocha)' size='Tall' quantity=1 modifiers=[]
name='Avocado Toast' size=None quantity=2 modifiers=[]
name='Blueberry Muffin' size=None quantity=2 modifiers=[]
name='Cappuccino' size='Venti' quantity=4 modifiers=[]
name='Frappe (Coffee)' size='Grande' quantity=1 modifiers=[]
name='Latte' size='Short' quantity=3 modifiers=[]
name='Blueberry Muffin' size=None quantity=2 modifiers=[]
name='Iced Coffee' size='Venti' quantity=1 modifiers=[]
name='Butter Croissant' size=None quantity=2 modifiers=[]
name='Hot Chocolate' size='Tall' quantity=2 modifiers=[]
name='Bagel' size=None quantity=1 modifiers=[]
name='Frappe (Coffee)' size='Venti' quantity=2 modifiers=[]
name='Cappuccino' size='Venti' quantity=4 modifiers=[]
name='Avocado Toast' size=None quantity=3 modifiers=[]
name='Frappe (Coffee)' size='Grande' quantity=4 modifiers=[]
name='Latte' size='Short' quantity=3 modifiers=[]
name='Avocado Toast' size=None quantity=2 modifiers=[]
name='Americano' size='Venti' quantity=1 modifiers=[]
name='Blueberry Muffin' size=None quantity=2 modifiers=[]
name='Butter Croissant' size=None quantity=1 modifiers=[]
name='Mocha' size='Grande' quantity=4 modifiers=[]
name='Iced Coffee' size='Short' quantity=1 modifiers=[]
name='Frappe (Coffee)' size='Short' quantity=1 modifiers=[]
name='Blueberry Muffin' size=None quantity=3 modifiers=[]
name='Green Tea' size='Grande' quantity=1 modifiers=[]
name='Caramel Macchiato' size='Trenta' quantity=3 modifiers=[]
name='Bagel' size=None quantity=3 modifiers=[]
name='Chai Latte' size='Tall' quantity=4 modifiers=[]
name='Bagel' size=None quantity=1 modifiers=[]
name='Latte' size='Trenta' quantity=1 modifiers=[]
name='Iced Coffee' size='Venti' quantity=2 modifiers=[]
name='Strawberry Smoothie' size='Grande' quantity=2 modifiers=[]
name='Flat White' size='Venti' quantity=5 modifiers=[]
name='Earl Grey Tea' size='Tall' quantity=2 modifiers=[]
name='Matcha Latte' size='Grande' quantity=2 modifiers=[]
name='Strawberry Smoothie' size='Grande' quantity=1 modifiers=[]
name='Avocado Toast' size=None quantity=3 modifiers=[]
name='Blueberry Muffin' size=None quantity=2 modifiers=[]
name='Green Tea' size='Grande' quantity=1 modifiers=[]
name='Bagel' size=None quantity=2 modifiers=[]
name='Avocado Toast' size=None quantity=2 modifiers=[]
name='Blueberry Muffin' size=None quantity=3 modifiers=[]
name='Bagel' size=None quantity=3 modifiers=[]
name='Green Tea' size='Short' quantity=5 modifiers=[]
name='Avocado Toast' size=None quantity=2 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=3 modifiers=[]
name='Flat White' size='Short' quantity=2 modifiers=[]
name='Drip Coffee' size='Venti' quantity=1 modifiers=[]
name='Bacon Gouda Sandwich' size=None quantity=2 modifiers=[]
name='Frappe (Coffee)' size='Grande' quantity=5 modifiers=[]
name='Avocado Toast' size=None quantity=3 modifiers=[]
name='Cold Brew' size='Trenta' quantity=2 modifiers=[]
name='Chai Latte' size='Short' quantity=3 modifiers=[]
name='Iced Coffee' size='Short' quantity=1 modifiers=[]
name='Blueberry Muffin' size=None quantity=4 modifiers=[]
name='Green Tea' size='Tall' quantity=5 modifiers=[]
name='Flat White' size='Venti' quantity=1 modifiers=[]
name='Mocha' size='Tall' quantity=2 modifiers=[]

In [1]:
from barista_bench.prompt.default import BaristaPrompt

%load_ext autoreload
%autoreload 2

In [4]:
prompt = BaristaPrompt('default.txt', ())
print(prompt)

You are a Barista POS System designed to take customer orders and output JSON corresponding to what the customer has ordered. The cafe that you are working with has the following menu and instructions:

# BARISTA BENCH: OFFICIAL MENU & RULES (V2)

## 1. HOT COFFEES
- Espresso: $3.00 (Default: Solo)
- Americano: $3.50
- Drip Coffee: $2.50
- Latte: $4.50 (Default: Whole Milk)
- Cappuccino: $4.50 (Default: Whole Milk)
- Flat White: $4.75 (Default: Whole Milk)
- Mocha: $5.00 (Default: Whole Milk, Whip)
- Caramel Macchiato: $5.25 (Default: Whole Milk, Drizzle)

## 2. COLD / BLENDED
- Cold Brew: $4.25
- Iced Coffee: $3.00
- Frappe (Coffee): $5.50 (Default: Whole Milk, Whip)
- Frappe (Mocha): $5.75 (Default: Whole Milk, Whip)
- Strawberry Smoothie: $6.00 (No Milk)

## 3. TEAS & OTHERS
- Chai Latte: $4.75 (Default: Whole Milk)
- Matcha Latte: $5.25 (Default: Whole Milk)
- Earl Grey Tea: $3.00
- Green Tea: $3.00
- Hot Chocolate: $4.00 (Default: Whole Milk, Whip)

## 4. FOOD (No modifiers allowed usually)
- Butter Croissant: $3.50
- Blueberry Muffin: $3.75
- Bagel: $2.50
- Avocado Toast: $7.00
- Bacon Gouda Sandwich: $5.50

## 5. SIZES (Drink Price Adjustments)
- Short (8oz): -$0.50
- Tall (12oz): +$0.00 (Base)
- Grande (16oz): +$0.50
- Venti (20oz): +$1.00
- Trenta (30oz): +$1.50 (Cold drinks only)

## 6. MODIFIERS
### Milks (Replaces default)
- Oat Milk: +$0.80
- Almond Milk: +$0.60
- Soy Milk: +$0.60
- Coconut Milk: +$0.70
- Breve (Half & Half): +$0.80
- Skim Milk: +$0.00

### Syrups (Add-on)
- Vanilla Syrup: +$0.50
- Caramel Syrup: +$0.50
- Hazelnut Syrup: +$0.50
- Peppermint Syrup: +$0.50
- Sugar Free Vanilla: +$0.50
- Classic Syrup: +$0.00

### Toppings / Texture
- Extra Shot: +$1.00
- Whip Cream: +$0.50
- No Whip: +$0.00
- Cold Foam: +$1.25
- Caramel Drizzle: +$0.50
- Extra Hot: +$0.00
- Light Ice: +$0.00
- No Ice: +$0.00

## 7. LOGIC RULES
- **Replacement:** If a user asks for a milk (e.g., Oat), it replaces the default.
- **Cancellation:** If a user says "No Whip" on a drink that has Whip (like Mocha), the price does not change, but "No Whip" is noted.
- **Double Mods:** Syrups stack (Vanilla + Caramel = +$1.00).
- **Food:** Food items do not have sizes.

Assume that the customer is always correct, if the customer ordered something it will be on the menu so choose the closest item on the menu.


FORMAT:
Return ONLY a JSON Object. Do not explain your work


{'$defs': {'Order': {'properties': {'name': {'title': 'Name', 'type': 'string'}, 'size': {'anyOf': [{'type': 'string'}, {'type': 'null'}], 'title': 'Size'}, 'quantity': {'title': 'Quantity', 'type': 'integer'}, 'modifiers': {'items': {'type': 'string'}, 'title': 'Modifiers', 'type': 'array'}}, 'required': ['name', 'size', 'quantity', 'modifiers'], 'title': 'Order', 'type': 'object'}}, 'properties': {'items': {'items': {'$ref': '#/$defs/Order'}, 'title': 'Items', 'type': 'array'}, 'total_price': {'title': 'Total Price', 'type': 'number'}}, 'required': ['items', 'total_price'], 'title': 'OrderList', 'type': 'object'}